apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-aws-monitor.fullname" . }}
  labels:
    {{- include "flask-aws-monitor.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flask-aws-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flask-aws-monitor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "flask-aws-monitor.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5001
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 8 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 8 }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: AWS_SECRET_ACCESS_KEY

